### ISSUE TITLE
The string loadfromtheme_desc can't be parsed by AMOS

### ISSUE THREAD

**Issue by mudrd8mz** [justinhunt/moodle-atto_snippet#1]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

This is really a current limitation on the AMOS side, but you may want to get rid of the concatenation operator now so that the plugin strings are registered with AMOS and can be translated by the community.

**Comment by justinhunt** [comment]
Thanks for letting me know about that. I had no idea. That should be fixed now in: https://github.com/justinhunt/moodle-atto_snippet/commit/881cde602e2712f80e26fddcff0b794befddba53
